# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mi's Blog
email: miguoliang61620@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I dream to code for the future of the human being in Google or Tesla.
  I dream to travel to all the world wonder of Civilization VI in the real world.
  I dream to taste all delicious food around the world with my wife.
  I dream to write something helpful for others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miguoliang.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: miguoliang
github_username:  miguoliang
google_analytics: UA-136531912-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
header_pages:
  - food.md
  - code.md
  - road.md
  - note.md
  - about.md

webmaster_verifications:
  google: c_dy3nviktjVLRn596isPsioYIJ-DJbwvi3a-IaPpUU
  bing: 1F25C7FEE6EA0EA3DFB94AB5C17E3965
  yandex: bfcf98bfa420e600
  baidu: wyRKL4aXeh